services:
  laravel:
    container_name: ${COMPOSE_PROJECT_NAME}-laravel
    build:
      context: ./src/laravel
      dockerfile: ../../docker/laravel/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-laravel
    ports:
      - "${LARAVEL_PORT:-8000}:8000"
    volumes:
      - type: bind
        source: ./src/laravel
        target: /app
    working_dir: /app
    restart: always
    networks:
      - app-network
  node:
    container_name: ${COMPOSE_PROJECT_NAME}-node
    image: node:22.16.0-alpine3.21
    volumes:
      - type: bind
        source: ./src/laravel
        target: /app
    working_dir: /app
    user: node
    tty: true
    restart: always
    networks:
      - app-network
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:17.5-alpine3.21
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    restart: always
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge